# Generated by Django 5.0.2 on 2024-02-26 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=50)),
                ('malumot', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=50)),
                ('fam', models.CharField(max_length=50)),
                ('yosh', models.IntegerField()),
                ('rasm', models.ImageField(upload_to='media')),
                ('lavozimi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfolder.type')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('rasm', models.ImageField(upload_to='media')),
                ('data', models.DateField()),
                ('tur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfolder.type')),
            ],
        ),
    ]
